### ISSUE TITLE
sass-migrator division **/* =  argument list too long: sass-migrator

### ISSUE THREAD

**Issue by dcrabbeYapily** [sass/migrator#188]
Can't use the migrator for `sass-migrator division **/*`

I get 
`argument list too long: sass-migrator`

thanks.

**Comment by jathak** [comment]
This is likely due to the glob matching so many files that it exceeds the maximum number of arguments allowed to a process.

Does a more specific glob like `**/*.scss` (or perhaps `lib/**/*.scss`, where `lib` is the directory your Sass files are in) work?

**Comment by jathak** [comment]
Closing this since it's due to a shell or OS restriction, not the migrator itself. We've updated the documentation to use `**/*.scss`. If you still run into this issue with that, you can try quoting it (e.g. `sass-migrator division '**/*.scss'`), which should let the migrator itself resolve the glob (make sure you're on the latest version though, since we previously had a bug that prevented this from working on Node).
