### ISSUE TITLE
Built-in glob resolution broken on Node

### ISSUE THREAD

**Issue by frattaro** [sass/migrator#189]
Running node 14.x on windows 10

Ran:
`npm i -g sass-migrator`
`sass-migrator division **/*`

Error> Unsupported operation: Recursive list is not supported in Node.js.

This is following the steps at https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration

**Comment by Dehairka** [comment]
same issue

**Comment by jathak** [comment]
It looks like's the migrator's support for globs is broken when running on Node. This isn't usually an issue on Mac and Linux, since shells will resolve the globs themselves, but Windows expects programs to do it themselves.

I'll try to find a fix, but for the time being, you can download the standalone release of the migrator [here](https://github.com/sass/migrator/releases/latest) and use that, which should work fine.

You'll also want to call it with `sass-migrator division **/*.scss` instead of what's listed in the documentation (I have a PR to update this out for review now in https://github.com/sass/sass-site/pull/545).

**Comment by frattaro** [comment]
Thanks -- tried that immediately after, filed #190 :)
