### ISSUE TITLE
Migrator mistakenly uses math.div instead of list.slash

### ISSUE THREAD

**Issue by tannermannjfit** [sass/migrator#205]
After running the migration command in our Bootstrap 4.6.0 project I noticed that in node_modules/bootstrap/scss/mixins/_forms.scss, math.div is used instead of list.slash on the background property.

Here is the code pre-migration:

````
.custom-select {
    @include form-validation-state-selector($state) {
      border-color: $color;

      @if $enable-validation-icons {
        padding-right: $custom-select-feedback-icon-padding-right;
        background: $custom-select-background, $custom-select-bg escape-svg($icon) $custom-select-feedback-icon-position / $custom-select-feedback-icon-size no-repeat;
      }

      &:focus {
        border-color: $color;
        box-shadow: 0 0 0 $input-focus-width rgba($color, .25);
      }
    }
  }
````

Here it is after (causes a compilation warning):

````
.custom-select {
    @include form-validation-state-selector($state) {
      border-color: $color;

      @if $enable-validation-icons {
        padding-right: $custom-select-feedback-icon-padding-right;
        background: $custom-select-background, $custom-select-bg escape-svg($icon) math.div($custom-select-feedback-icon-position, $custom-select-feedback-icon-size) no-repeat;
      }

      &:focus {
        border-color: $color;
        box-shadow: 0 0 0 $input-focus-width rgba($color, .25);
      }
    }
  }
````

**Comment by jathak** [comment]
Since the migrator only does _static_ analysis, it's not possible for it to determine whether the inputs to a given slash operation are numbers or strings. Since it's currently much more common for the slash operation to be division, and `math.div` currently operates identically to the current behavior of the slash operator, the migrator defaults to migrating to `math.div` unless it can statically guarantee that it's not division (e.g. when one of the operands is a literal string).

If you'd like the migrator to only migrate slash operations that it's sure are division, you can pass the `--pessimistic` flag, but that will skip migrating many slash operations that _are_ division when executed, but can't be statically guaranteed by the migrator.

**Comment by mehdibehvar** [comment]
can we change correct it manually in node_modules/bootstrap/scss/mixins/_forms.scss?

**Comment by jathak** [comment]
You generally shouldn't be migrating code in node_modules, as that should be fixed upstream. If you're just trying to prevent the deprecation warnings from this code, you can pass `--quiet-deps` to Sass.

**Comment by mehdibehvar** [comment]
thank you for your answer
