### ISSUE TITLE
Wrong division patching

### ISSUE THREAD

**Issue by beruic** [sass/migrator#208]
After patching divisions on Bootstrap 4.6.0 scss files I get this:

```
$ npx gulp build_css                                 
[13:34:48] Using gulpfile ~/git/my-project/gulpfile.js
[13:34:48] Starting 'build_css'...
WARNING: math.div() will only support number arguments in a future release.
Use list.slash() instead for a slash separator.

    ╷
120 │         background: $custom-select-background, $custom-select-bg escape-svg($icon) math.div($custom-select-feedback-icon-position, $custom-select-feedback-icon-size) no-repeat;
    │                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/mixins/_forms.scss 120:84  @content
    node_modules/bootstrap/scss/mixins/_forms.scss 37:7    form-validation-state-selector()
    node_modules/bootstrap/scss/mixins/_forms.scss 115:5   form-validation-state()
    node_modules/bootstrap/scss/_forms.scss 263:3          @import
    node_modules/bootstrap/scss/bootstrap.scss 18:9        @import
    sass/main.scss 21:9                                    root stylesheet

[13:34:51] Finished 'build_css' after 2.61 s
```

Shouldn't the migrator be able to handle this?

**Comment by crysislinux** [comment]
Though the warning is clear by itself, I am not able to find any information about the warning, even the sass `math.div` doc shows usage like `math.div(10px, 5px)`.

**Comment by jathak** [comment]
This is unfortunately working-as-intended within the scope of the migrator. The migrator only does local static analysis of the code being migrated, so it can't definitively determine whether the values passed to a given slash operation are numbers or not.

Because slash operations on numbers are much more common than those on non-numbers and migrating to `math.div` won't outright break your code (since for the time being, `math.div` supports non-numbers, just with a deprecation warning), the default behavior of the migrator is to migrate all slash operations to `math.div` unless it definitively knows that one or more of the operands is not a number (e.g. one is a string literal).

If you'd like, you can pass `--pessimistic` to the migrator, which will only migrate slash operations that can be statically determined to be on numbers, but that will miss a lot of valid division operations, so we generally recommend against it.

**Comment by beruic** [comment]
@jathak I have tried `--pessimistic`, ant it makes it worse.

I'm just wondering why this cannot be fixed when the compiler can tell me that it is wrong. Why not just use the compiler in the migrator, since the it seems to detect this fine?

The thing is that I am using this as a part of build, as I need to migrate Bootstrap 4.6.0 in a clean environment every time our pipeline builds our software.

I'd expect most to only need to migrate once, but I do wonder if there are many more with similar use cases.

My alternative is to add all of Bootstrap 4.60 to our repository, and I'd rather avoid poluting our tree more than necessary.

**Comment by jathak** [comment]
Unfortunately, the migrator is not intended for completely automated use. It's designed to get you most of the way there, but with manual changes required for some code. While theoretically possible (at least for the division migrator; it would be a complete non-starter for the module system migrator), fully compiling every file we wish to migrate would add a lot of complexity that's not worth it given our intended use case.

We generally recommend running the migrator only over your own code, not third-party dependencies. If you just want to silence the deprecation warnings from third-party code, you can instead just pass the `--quiet-deps` flag to the compiler.
