### ISSUE TITLE
Don't migrate division inside calc expressions

### ISSUE THREAD

**Issue by hoorayimhelping** [sass/migrator#216]
When using `sass-migrator division` against a file with the following expression:

```scss
margin-left: calc(var(--space-s-l) / -2);
margin-right: calc(var(--space-s-l) / -2);
```

It migrates it to:
```scss
margin-left: calc(math.div(var(--space-s-l), -2));
margin-right: calc(math.div(var(--space-s-l), -2));
```

Which then generates the following warning:
```
Warning: math.div() will only support number arguments in a future release.
Use list.slash() instead for a slash separator.

 margin-left: calc(math.div(var(--space-s-l), -2));
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The same file had the following expression:

```scss
padding-left: calc(var(--space-s-l) / 2);
padding-right: calc(var(--space-s-l) / 2);
```

which was correctly changed to:

```scss
padding-left: calc(var(--space-s-l) * 0.5);
padding-right: calc(var(--space-s-l) * 0.5);
```

which makes it seem pretty clear that it was the negative number causing issues.

**Comment by jathak** [comment]
While we could probably add support for migrating common negative division expressions to fractional multiplication, the true bug here is that we should leave `/` as-is when it is inside a `calc` expression.

I believe this was the case when the migrator was written, since SassScript was previously not evaluated within `calc`, but now that first-class calc is a thing, the parser is treating them as regular Sass expressions, so we likely need to update the migrator to specifically ignore `calc`.
