### ISSUE TITLE
Add the ability to migrate from indent-based SASS to brace-based SCSS

### ISSUE THREAD

**Issue by Atulin** [sass/migrator#255]
I'm currently trying to migrate my project from SASS to SCSS since we decided it will improve maintainability. We can get 80% there with a Python script and some regex (adding semicolons, turning `+mixin` into `@include mixin`, etc) but things like adding braces need to still be done manually since there isn't really a good way to regex our way around it.

**Comment by jathak** [comment]
We used to have this with Ruby Sass, but it was a lot of work to maintain as the AST changed, so we made a conscious choice not to spend the effort on bringing it over to Dart Sass.

The migrator is built around migrations that can be expressed in terms of patches to the source code, while this specific migration would instead involve pretty-printing the AST. Someone else could implement it using the `sass_api` package (essentially creating a formatter that lets you choose between outputting the indented or SCSS syntax), but it's not something we're likely to have the bandwidth to create and maintain ourselves, and it would be its own package, rather than part of the migrator.

**Comment by Atulin** [comment]
Understandable. I'll stick to my Python script for semis and mixins, and add braces manually, then.
<details>
<summary>Script here, if anybody needs it in the future</summary>
```py
import os
import re

""" Adds semicolons where needed
in:  `background-color: red`
out: `background-color: red;`
"""
semicolon_regex = re.compile(r'([a-z-]+): (.+)\n')

""" Migrates mixin references from short syntax
in:  `+foo.bar`
out: `@include foo.bar;`
"""
mixin_regex = re.compile(r'\+\s?([a-z]+\.[a-z\-]+)\n')

""" Adds semicolons specifically to imports
in:  `@use '../foo' as bar`
out: `@use '../foo' as bar;`
"""
imports_regex = re.compile(r'(@use ["\'].+["\'] as [a-z\-]+)\n')

folder = input('Enter source folder: ').strip()

print('Leave file name empty to exit')
while True:
    file = input('Enter file: ').strip()

    if len(file) <= 0:
        break

    if not file.endswith('.sass'):
        file = f'{file}.sass'

    path = os.path.join(folder, file)

    print(f'Migrating {path}')

    with open(path, 'r+', encoding='utf8') as f:
        old = f.read()
        new = old + '\n'
        new = semicolon_regex.sub(r'\1: \2;\n', new)
        new = mixin_regex.sub(r'@include \1;\n', new)
        new = imports_regex.sub(r'\1;\n', new)
        f.seek(0)
        f.write(new)
        print('Done!')

print('Exiting')
```
</details>
