### ISSUE TITLE
Gracefully handle members that are already pseudo-private

### ISSUE THREAD

**Issue by nex3** [sass/migrator#48]
Some libraries already prefix members with `_` or `-` to indicate that they're library-private. If any of these members are used across modules, though, leaving their names as-is will break, since they're now treated as module-private. The migrator should rename such members to remove the leading `_` or `-`.

Once https://github.com/sass/migrator/issues/47 is done, the migrator should also guarantee that members that used to start with `_` or `-` are never forwarded through top-level entrypoints (using `hide` if necessary).

**Comment by jathak** [comment]
This is tricky, because the migrator currently assumes that a stylesheet's migrated contents are fixed once it finishes visiting it, but we don't know whether to treat a member as library-private until we see it referenced in another module (which would usually be after the declaring stylesheet's contents are fixed).

Would just adding a flag to treat all members that start with `_` or `-` as library-private be good enough?

If not, this could maybe be done by leaving each stylesheet's migration as a list of patches until the very end, but we would also need to keep track of all local references to all members that start with `_` or `-` so that we could patch them if we need to change the name, so this would add a lot of complexity that I'd rather avoid if making this all-or-nothing is good enough.

**Comment by nex3** [comment]
> Would just adding a flag to treat all members that start with `_` or `-` as library-private be good enough?

That's not ideal, but I hear you about adding too much extra complexity, so I guess this is probably the best compromise.

**Comment by nex3** [comment]
Just a heads-up: once you start working on this, make sure to test how it interacts with https://github.com/sass/migrator/pull/72. It's common for libraries to use one prefix (e.g. `mat-`) for package-public members, and the same prefix with a leading `_` (e.g. `_mat-`) for package-private members.
